version: 2
updates:
  - package-ecosystem: docker
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: uv
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: weekly
